"""Add heuristic detection fields to attack_log

Revision ID: 5f45e7501aa3
Revises: 001_sqlite
Create Date: 2025-08-15 13:20:21.600412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f45e7501aa3'
down_revision = '001_sqlite'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attack_logs', sa.Column('attack_type', sa.String(length=50), nullable=True))
    op.add_column('attack_logs', sa.Column('attack_severity', sa.String(length=20), nullable=True))
    op.add_column('attack_logs', sa.Column('attack_description', sa.Text(), nullable=True))
    op.add_column('attack_logs', sa.Column('suspicious_payloads', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('attack_logs', sa.Column('heuristic_anomalies', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attack_logs', 'heuristic_anomalies')
    op.drop_column('attack_logs', 'suspicious_payloads')
    op.drop_column('attack_logs', 'attack_description')
    op.drop_column('attack_logs', 'attack_severity')
    op.drop_column('attack_logs', 'attack_type')
    # ### end Alembic commands ###